"""Pre-built index of Tripletex API operations for the find_api sub-agent.

The index is generated by scripts/build_api_index.py from the Tripletex OpenAPI spec
and stored as api_index_data.json (a package resource). At runtime, keyword matching
selects relevant tag groups and formats them as text for the sub-agent context.
"""

from __future__ import annotations

import json
import re
from importlib import resources
from typing import Any


class ApiIndex:
    """Searchable index of Tripletex API operations grouped by resource tag."""

    def __init__(self, data: dict[str, list[dict[str, Any]]]) -> None:
        self.data = data
        self._tag_keywords: dict[str, set[str]] = {}
        for tag, operations in data.items():
            keywords = set(_tokenize(tag))
            for op in operations:
                keywords.update(_tokenize(op.get("summary", "")))
            self._tag_keywords[tag] = keywords

    @classmethod
    def load_default(cls) -> ApiIndex:
        text = resources.files("ai_accounting_agent").joinpath("api_index_data.json").read_text(encoding="utf-8")
        return cls(json.loads(text))

    def search(self, need: str, max_groups: int = 5) -> tuple[list[str], str]:
        """Match need keywords against tags and operation summaries.

        Returns:
            (matched_tags, formatted_text) — the tag names that matched and
            a formatted string of their operations for the sub-agent.
        """
        query_tokens = set(_tokenize(need))
        if not query_tokens:
            return [], ""

        scored: list[tuple[float, str]] = []
        for tag, tag_keywords in self._tag_keywords.items():
            overlap = query_tokens & tag_keywords
            if not overlap:
                continue
            tag_tokens = set(_tokenize(tag))
            tag_overlap = query_tokens & tag_tokens
            score = len(overlap) + len(tag_overlap) * 3
            scored.append((score, tag))

        scored.sort(key=lambda x: -x[0])
        top_tags = [tag for _, tag in scored[:max_groups]]

        if not top_tags:
            return [], ""

        formatted = _format_tag_groups(self.data, top_tags)
        return top_tags, formatted


def _tokenize(text: str) -> list[str]:
    """Extract lowercase alphanumeric tokens (3+ chars) from text."""
    return [t for t in re.findall(r"[a-z0-9]+", text.lower()) if len(t) >= 3]


def _format_tag_groups(data: dict[str, list[dict[str, Any]]], tags: list[str]) -> str:
    """Format selected tag groups as readable text for the sub-agent."""
    sections: list[str] = []
    for tag in tags:
        operations = data.get(tag, [])
        if not operations:
            continue
        lines = [f"## Resource: {tag}", ""]
        for op in operations:
            method = op.get("method", "?")
            path = op.get("path", "?")
            summary = op.get("summary", "")
            lines.append(f"### {method} {path}")
            if summary:
                lines.append(f"Summary: {summary}")

            params = op.get("parameters", [])
            if params:
                lines.append("Parameters:")
                for p in params:
                    required = " (REQUIRED)" if p.get("required") else ""
                    ptype = p.get("type", "")
                    desc = p.get("description", "")
                    lines.append(f"  - {p['name']}: {ptype}{required} — {desc}")

            body = op.get("request_body")
            if body:
                lines.append("Request body schema:")
                lines.append(_format_schema(body, indent=2))

            lines.append("")
        sections.append("\n".join(lines))

    return "\n---\n\n".join(sections)


def _format_schema(schema: dict[str, Any], indent: int = 0) -> str:
    """Format a simplified JSON schema as readable text."""
    prefix = " " * indent
    lines: list[str] = []

    required_fields = set(schema.get("required", []))
    props = schema.get("properties", {})

    if props:
        for name, prop in props.items():
            req_marker = " (REQUIRED)" if name in required_fields else ""
            ptype = prop.get("type", "")
            fmt = prop.get("format", "")
            desc = prop.get("description", "")
            ref = prop.get("$ref", "")

            type_str = ptype
            if fmt:
                type_str = f"{ptype}({fmt})"
            if ref:
                type_str = f"object → {ref}"
            if prop.get("enum"):
                type_str = f"enum: {prop['enum']}"

            line = f"{prefix}- {name}: {type_str}{req_marker}"
            if desc:
                line += f" — {desc}"
            lines.append(line)

            nested_props = prop.get("properties")
            if nested_props:
                lines.append(_format_schema(prop, indent=indent + 4))

            items = prop.get("items")
            if items:
                items_ref = items.get("$ref", "")
                items_type = items.get("type", "object")
                if items_ref:
                    lines.append(f"{prefix}    items: object → {items_ref}")
                elif items.get("properties"):
                    lines.append(f"{prefix}    items:")
                    lines.append(_format_schema(items, indent=indent + 6))
                else:
                    lines.append(f"{prefix}    items: {items_type}")
    elif schema.get("type"):
        lines.append(f"{prefix}type: {schema['type']}")

    return "\n".join(lines)


_api_index_cache: ApiIndex | None = None


def get_api_index() -> ApiIndex:
    """Get the cached API index singleton."""
    global _api_index_cache
    if _api_index_cache is None:
        _api_index_cache = ApiIndex.load_default()
    return _api_index_cache
